delete from "public"."modules";
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (18,'login','','','','',0,'N','Y','N','N','N','N','3/17/2011','3/25/2011','Y','Y','','N','','','N','Login','Y','Y','N','N',35,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (1,'dashboard','','','Dashboard','icon-home',0,'Y','Y','N','N','N','N','8/5/2011','4/3/2013','Y','Y','','N','Dashboard','','N','Dashboard','Y','Y','N','N',0,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (116,'users','','','','',0,'Y','Y','N','N','N','N','12/8/2013','12/8/2013','N','N','','N','','','N','Users','Y','Y','N','N',0,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (131,'newsletterleads','Manage Newsletter Leads','','','',90,'Y','Y','N','N','N','N','10/18/2014','10/18/2014','Y','Y','','N','','','Y','Newsletterleads','Y','Y','N','N',36,'var_email') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (149,'campus_buzz','Manage Campus Buzz','Add Buzz','Campus Buzz Management','icon-file',0,'Y','Y','N','N','N','N','10/17/2014','10/18/2014','Y','Y',''' ''','N',''' ''','campus_buzz','Y','campus_buzz','Y','Y','Y','N',10,'var_title') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (4,'contactus','Manage Contact Information','','','',0,'Y','Y','N','N','N','N','2/9/2012','4/4/2013','Y','Y','','N','','','Y','Contact Information','Y','Y','N','N',5,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (11,'trashmanager','Manage Trash Manager','','','',8,'Y','Y','N','N','N','N','3/17/2011','4/4/2013','N','Y','','N','','','N','Trash Manager','Y','Y','N','N',38,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (10,'settings/logmanager','Manage Log Manager','','','',8,'Y','Y','N','N','N','N','4/15/2011','4/4/2013','N','Y','index?module=settings','N','','','N','Log Manager','Y','Y','N','N',38,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (150,'campus_buzz_gallery','Manage Buzz Gallery','Add New Image','','icon-file',0,'Y','Y','N','N','N','N','10/17/2014','10/18/2014','Y','Y',''' ''','N',''' ''','campus_buzz_gallery','Y','campus_buzz_gallery','N','Y','Y','N',11,'var_title') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (141,'university_management','Manage University','Add University','University Management','icon-file',0,'Y','Y','N','N','N','N','10/17/2014','10/18/2014','Y','Y','','N','','university_management','Y','university_management','Y','Y','Y','N',2,'var_title') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (133,'banner','Manage Home Banners','Add Home Banner','Banners','icon-file',0,'Y','Y','N','N','N','N','5/8/2014','5/8/2014','N','Y','module=banner','Y','banner','banner','Y','Home Banners','Y','Y','Y','N',55,'var_title') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (17,'module','Manage Modules','Add Module','Module','icon-home',0,'Y','Y','N','N','N','N','4/2/2013','4/4/2013','Y','Y','','N','','modules','N','Module','N','Y','N','N',58,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (90,'contactusleads','Manage Contact Us Leads','','Leads','icon-user-md',0,'Y','Y','N','N','N','N','7/31/2013','7/31/2013','N','Y','','Y','','contactdetails','Y','Contact Us Leads','Y','Y','Y','N',36,'var_name') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (3,'commonfile','Manage Common Files','Add Common File','Common File','icon-file',0,'Y','Y','N','N','N','N','12/6/2012','4/4/2013','N','Y','','N','','commonfile','Y','Common Files','Y','Y','Y','N',3,'var_title') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (143,'post_category','Manage Post Category','Add Post Category','Post Category Management','icon-file',0,'Y','Y','N','N','N','N','10/17/2014','10/18/2014','Y','Y',''' ''','N',''' ''','post_category','Y','post_category','Y','Y','Y','N',6,'var_title') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (144,'post_management','Manage Post','Add Post','Post Management','icon-file',0,'Y','Y','N','N','N','N','10/17/2014','10/18/2014','Y','Y',''' ''','N',''' ''','post_management','Y','post_management','Y','Y','Y','N',7,'var_title') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (145,'webservice','','','','',0,'Y','Y','N','N','N','N','4/18/2014','4/18/2014','Y','Y','','N','','','Y','Web Services','Y','Y','N','N',1,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (2,'pages','Manage Pages','Add Page','Pages','icon-file',0,'Y','Y','N','N','N','N','3/23/2011','3/28/2013','N','Y','module=pages','Y','stream','pages','Y','Pages','Y','Y','Y','N',1,'var_pagename') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (7,'settings','Change Profile','','Settings','',8,'Y','Y','N','N','N','N','3/28/2013','4/4/2013','N','Y','','N','','users','N','Change Profile','Y','Y','N','N',39,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (8,'settings/systemsettings','Manage System Settings','','Settings','icon-cogs',0,'Y','Y','N','N','N','N','3/28/2013','3/29/2013','N','Y','','N','','','N','Settings','Y','Y','N','N',40,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (146,'post_gallery','Manage Post Gallery','Add Post Image','','icon-file',0,'Y','Y','N','N','N','N','10/17/2014','10/18/2014','Y','Y',''' ''','N',''' ''','post_gallery','Y','post_gallery','N','Y','Y','N',6,'var_title') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (99,'user_management/groupaccess','Manage Group Access','Add Group Access','User Management','',98,'Y','Y','N','N','N','N','8/22/2013','8/22/2013','N','Y','','N','','','Y','Group Access','Y','Y','N','N',42,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (100,'user_management/modcontrol','Assign Module Action','','User Management','',98,'Y','Y','N','N','N','N','8/22/2013','8/22/2013','N','Y','index.php?module=modcontrol','N','','','N','Assign Module Action','Y','Y','N','N',43,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (147,'campus_deal','Manage Campus Deals','Add Deal','Campus Deal Management','icon-file',0,'Y','Y','N','N','N','N','10/17/2014','10/18/2014','Y','Y',''' ''','N',''' ''','campus_deal','Y','campus_deal','Y','Y','Y','N',8,'var_title') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (98,'user_management/accesscontrol','Manage Users','Add User','User Management','icon-file',0,'Y','Y','N','N','N','N','8/22/2013','8/22/2013','Y','Y','','N','','','Y','Staff','Y','Y','N','N',36,'') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (142,'job_management','Manage Jobs','Add Job','Job Management','icon-file',0,'Y','Y','N','N','N','N','10/17/2014','10/18/2014','Y','Y','','N','','job_management','Y','job_management','Y','Y','Y','N',5,'var_title') ;
insert into "public"."modules" ("int_glcode","var_modulename","var_module_listing","var_module_form_listing","var_header_text","var_header_class","fk_module","chr_edit_delete","chr_publish","chr_delete","chr_star","chr_cached","chr_read","dt_createdate","dt_modifydate","chr_adminpanel_module","chr_show_trashmanager","var_link","chr_seoprefix","var_seoprefix","var_tablename","chr_filterflag","chr_pro_modulename","chr_menu","chr_group_access","chr_gallerymodule_flag","chr_custom","int_displayorder","var_field") 
  values (148,'campus_gallery','Manage Deals Gallery','Add New Image','','icon-file',0,'Y','Y','N','N','N','N','10/17/2014','10/18/2014','Y','Y',''' ''','N',''' ''','campus_gallery','Y','campus_gallery','N','Y','Y','N',9,'var_title') ;
